import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Data } from "./api/hello";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [message, setMessage] = useState<string>("");

  const getMessage = async () => {
    const response = await fetch("/api/hello");
    const data: Data = await response.json();
    setMessage(data.message);
  };

  useEffect(() => {
    getMessage();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
      <h2>{message}</h2>
    </>
  );
}
